In [6]:
import numpy as np 
#one's matric
mx_1s = np.array([[1,2,3],[5,6,7],[9,10,11]])
print(mx_1s)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [9]:
#an other way to creat one's matrix
mx_1s = np.ones(5) #by default fload type data type
print(mx_1s) 


[1. 1. 1. 1. 1.]


In [11]:
mx_1s.dtype

dtype('float64')

In [13]:
mx_1s = np.ones((3,4)) #shape row and column 
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
mx_1s = np.ones((3,4),dtype = int) #int type one's matric
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [17]:
#Zero Matrix
mx_0s = np.zeros((4,6))
print(mx_0s)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [19]:
#converson data type from default(float) to bool
mx_0s = np.zeros((4,6),dtype = bool)
print(mx_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [21]:
mx_0s = np.zeros((4,6),dtype = str) #float to string
print(mx_0s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [23]:
em_str = ''
print(bool(em_str))

False


In [24]:
#Empty Matrix       #randomly value defaulty inserted
em_mx = np.empty((3,3))
print(em_mx)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 5.27662110e-321]
 [8.34451503e-308 2.46151512e-312 3.33771434e-307]]
