# Numpy Function 


In [3]:
import numpy as np


# arange()

In [6]:
# np.arange(Start,End,Steps)
ar_1d = np.arange(1,13)
print(ar_1d)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
even_ar = np.arange(2,13,2)
print(even_ar)

[ 2  4  6  8 10 12]


# linespace()


In [10]:
ln_function = np.linspace(1,5,4)
print(ln_function)

[1.         2.33333333 3.66666667 5.        ]


# Reshape()

In [16]:
# print(ar_1d)
ar_2d = ar_1d.reshape(3,4)
print(ar_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
ar_3d = ar_1d.reshape(2,3,2) 
print(ar_3d)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [27]:
ar_twod= np.arange(1,13).reshape(2,6)
print(ar_twod)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel()

In [25]:
arr = ar_twod.ravel()
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# flatten()

In [26]:
arr2 = ar_twod.flatten()
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# transpose

In [34]:
tr_mx = ar_twod.transpose() #Row convert into Columns
print(tr_mx)

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]
